// src/quizData.js

export const quizQuestions = [
    // === MULTIPLE CHOICE ===
    { question: "Which gas makes up the majority of Earth's atmosphere?", answers: ["Nitrogen", "Oxygen", "Carbon Dioxide", "Hydrogen"], correct: "Nitrogen" },
    { question: "What is the largest organ in the human body?", answers: ["Skin", "Liver", "Brain", "Lungs"], correct: "Skin" },
    { question: "Which blood group is known as the universal donor?", answers: ["O Negative", "A Positive", "B Negative", "AB Positive"], correct: "O Negative" },
    { question: "What is the capital city of France?", answers: ["Paris", "Marseille", "Lyon", "Nice"], correct: "Paris" },
    { question: "How many hours are there in a standard day?", answers: ["24", "12", "48", "36"], correct: "24" },
    { question: "Which layer of Earth's atmosphere contains the ozone layer?", answers: ["Stratosphere", "Troposphere", "Mesosphere", "Thermosphere"], correct: "Stratosphere" },
    { question: "What is the chemical symbol for the element Hydrogen?", answers: ["H", "Hy", "He", "Hg"], correct: "H" },
    { question: "Which planet is closest to our Sun?", answers: ["Mercury", "Venus", "Mars", "Earth"], correct: "Mercury" },
    { question: "What is the primary currency used in Japan?", answers: ["Yen", "Yuan", "Won", "Dollar"], correct: "Yen" },
    { question: "How many continents are there on planet Earth?", answers: ["7", "5", "6", "8"], correct: "7" },
    { question: "What is the main sugar found in milk?", answers: ["Lactose", "Glucose", "Fructose", "Sucrose"], correct: "Lactose" },
    { question: "Which historical civilization built the great Colosseum?", answers: ["Romans", "Greeks", "Egyptians", "Aztecs"], correct: "Romans" },
    { question: "What pigment gives plants their green coloration?", answers: ["Chlorophyll", "Carotene", "Xanthophyll", "Melanin"], correct: "Chlorophyll" },
    { question: "What is the capital city of Italy?", answers: ["Rome", "Milan", "Naples", "Venice"], correct: "Rome" },
    { question: "Which standard metric unit measures electrical resistance?", answers: ["Ohm", "Volt", "Ampere", "Watt"], correct: "Ohm" },
    { question: "How many primary colors are there in traditional paint mixing?", answers: ["3", "4", "5", "6"], correct: "3" },
    { question: "Which geometric shape has exactly three straight sides?", answers: ["Triangle", "Square", "Pentagon", "Hexagon"], correct: "Triangle" },
    { question: "What is the capital city of Japan?", answers: ["Tokyo", "Kyoto", "Osaka", "Nagoya"], correct: "Tokyo" },
    { question: "Which microscopic blood components help clot wounds?", answers: ["Platelets", "Red blood cells", "White blood cells", "Plasma"], correct: "Platelets" },
    { question: "What is the frozen, solid state of water called?", answers: ["Ice", "Steam", "Liquid", "Vapor"], correct: "Ice" },
    { question: "Which heavy organ detoxifies chemicals in the human body?", answers: ["Liver", "Kidney", "Spleen", "Pancreas"], correct: "Liver" },
    { question: "What primary gas do humans breathe out as waste?", answers: ["Carbon Dioxide", "Oxygen", "Nitrogen", "Methane"], correct: "Carbon Dioxide" },
    { question: "Which European country uses the currency called the Forint?", answers: ["Hungary", "Poland", "Czech Republic", "Romania"], correct: "Hungary" },
    { question: "What is the closest celestial satellite to planet Earth?", answers: ["The Moon", "The Sun", "Mars", "Venus"], correct: "The Moon" },
    { question: "Which primary physical force holds planets in their orbits?", answers: ["Gravity", "Magnetism", "Friction", "Inertia"], correct: "Gravity" },
    { question: "Which country has the longest coastline in the world?", answers: ["Russia", "Canada", "Australia", "United States"], correct: "Canada" },
    { question: "How many hearts does a standard octopus have?", answers: ["One", "Three", "Two", "Four"], correct: "Three" },
    { question: "What year was the first commercial iPhone released by Apple?", answers: ["2005", "2007", "2008", "2010"], correct: "2007" },
    { question: "Which planetary body is widely nicknamed the Red Planet?", answers: ["Venus", "Mars", "Jupiter", "Saturn"], correct: "Mars" },
    { question: "What is the capital city of Spain?", answers: ["Barcelona", "Madrid", "Valencia", "Seville"], correct: "Madrid" },
    { question: "Which heavy element has the standard chemical symbol 'Pb'?", answers: ["Phosphorus", "Lead", "Plutonium", "Platinum"], correct: "Lead" },
    { question: "What is the longest river running through our world?", answers: ["Amazon River", "Nile River", "Mississippi River", "Yangtze River"], correct: "Nile River" },
    { question: "Which specific gas is produced during plant photosynthesis?", answers: ["Carbon Dioxide", "Oxygen", "Nitrogen", "Hydrogen"], correct: "Oxygen" },
    { question: "What is the capital city of Germany?", answers: ["Munich", "Berlin", "Frankfurt", "Hamburg"], correct: "Berlin" },
    { question: "Which specific component inside animal cells acts as the powerhouse?", answers: ["Nucleus", "Mitochondria", "Ribosome", "Golgi Apparatus"], correct: "Mitochondria" },
    { question: "What structure forms the protective hard outer shell of insects?", answers: ["Endoskeleton", "Exoskeleton", "Cartilage", "Skin"], correct: "Exoskeleton" },
    { question: "Which planet is the massive, largest one in our solar system?", answers: ["Saturn", "Jupiter", "Neptune", "Uranus"], correct: "Jupiter" },
    { question: "What is the chemical symbol for the element Sodium?", answers: ["S", "Na", "So", "Sd"], correct: "Na" },
    { question: "Which specific mammal is natively capable of true powered flight?", answers: ["Flying Squirrel", "Bat", "Eagle", "Owl"], correct: "Bat" },
    { question: "What specific fluid type circulates through a plant's vascular tissue?", answers: ["Water", "Sap", "Blood", "Chlorophyll"], correct: "Sap" },
    { question: "Which specific device converts mechanical motion into electricity?", answers: ["Motor", "Generator", "Transformer", "Battery"], correct: "Generator" },
    { question: "What is the dynamic center core area of an atom called?", answers: ["Electron Cloud", "Nucleus", "Proton", "Neutron"], correct: "Nucleus" },
    { question: "Which active nutrient group builds up muscle tissues?", answers: ["Carbohydrates", "Proteins", "Fats", "Vitamins"], correct: "Proteins" },
    { question: "What is the capital city of the United Kingdom?", answers: ["Edinburgh", "London", "Manchester", "Dublin"], correct: "London" },
    { question: "Which natural material is traditionally used to manufacture paper sheets?", answers: ["Plastic", "Wood", "Cotton", "Hemp"], correct: "Wood" },
    { question: "What temperature scale sets the water freezing baseline at 32 degrees?", answers: ["Celsius", "Fahrenheit", "Kelvin", "Rankine"], correct: "Fahrenheit" },
    { question: "Which microscopic cells carry vital oxygen around our body?", answers: ["White Blood Cells", "Red Blood Cells", "Platelets", "Plasma Cells"], correct: "Red Blood Cells" },
    { question: "What mathematical ratio is approximately equal to 3.14159?", answers: ["Golden Ratio", "Pi", "Euler Number", "Square Root of 2"], correct: "Pi" },
    { question: "Which chemical element possesses the structural symbol 'Fe'?", answers: ["Fluorine", "Iron", "Ferrum", "Lead"], correct: "Iron" },
    { question: "What specific device breaks up white sunlight into rainbow bands?", answers: ["Mirror", "Prism", "Lens", "Filter"], correct: "Prism" },
    { question: "Which chess piece is strictly restricted to moving only diagonally?", answers: ["Rook", "Knight", "Bishop", "Queen"], correct: "Bishop" },
    { question: "What is the hardest natural substance found on planet Earth?", answers: ["Gold", "Iron", "Diamond", "Quartz"], correct: "Diamond" },
    { question: "Which famous historic artist painted the iconic 'Mona Lisa'?", answers: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"], correct: "Leonardo da Vinci" },
    { question: "What is the official capital city of Canada?", answers: ["Toronto", "Vancouver", "Ottawa", "Montreal"], correct: "Ottawa" },
    { question: "How many total elements are currently verified on the Periodic Table?", answers: ["108", "115", "118", "120"], correct: "118" },
    { question: "What is the chemical symbol for the element Gold?", answers: ["Gd", "Ag", "Au", "Go"], correct: "Au" },
    { question: "Which specific dynamic instrument measures earthquake intensities?", answers: ["Barometer", "Thermometer", "Seismograph", "Anemometer"], correct: "Seismograph" },
    { question: "What primary acid type is found inside human stomach fluids?", answers: ["Sulfuric Acid", "Nitric Acid", "Hydrochloric Acid", "Acetic Acid"], correct: "Hydrochloric Acid" },
    { question: "What year did the historic Titanic vessel encounter an iceberg?", answers: ["1905", "1910", "1912", "1920"], correct: "1912" },
    { question: "Which chemical element holds the single-letter symbol 'K'?", answers: ["Krypton", "Calcium", "Potassium", "Phosphorus"], correct: "Potassium" },
    { question: "What structural tissue framework links human bones to other bones?", answers: ["Muscle", "Tendon", "Ligament", "Cartilage"], correct: "Ligament" },
    { question: "Which vast planetary ocean is the deepest one on Earth?", answers: ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"], correct: "Pacific Ocean" },
    { question: "What basic temperature setting defines absolute zero in Celsius?", answers: ["0 °C", "-100 °C", "-273.15 °C", "-300 °C"], correct: "-273.15 °C" },
    { question: "Which structural gas type feeds clean combustion inside stars?", answers: ["Helium", "Oxygen", "Hydrogen", "Nitrogen"], correct: "Hydrogen" },
    { question: "What is the primary standard monetary unit of the European Union?", answers: ["Pound", "Dollar", "Euro", "Franc"], correct: "Euro" },
    { question: "Which historical scientist drafted the foundational Laws of Motion?", answers: ["Albert Einstein", "Galileo Galilei", "Isaac Newton", "Nikola Tesla"], correct: "Isaac Newton" },
    { question: "What baseline numeric pH level defines a perfectly neutral fluid?", answers: ["0", "5", "7", "14"], correct: "7" },
    { question: "Which instrument tracks absolute changes in atmospheric air pressures?", answers: ["Hygrometer", "Thermometer", "Barometer", "Altimeter"], correct: "Barometer" },
    { question: "What specific geometric term describes a full 90-degree angle?", answers: ["Acute Angle", "Obtuse Angle", "Right Angle", "Straight Angle"], correct: "Right Angle" },
    { question: "Which massive mammal holds the record as the largest on Earth?", answers: ["African Elephant", "Humpback Whale", "Blue Whale", "Colossal Squid"], correct: "Blue Whale" },
    { question: "What is the base currency used inside South Africa?", answers: ["Dollar", "Pound", "Rand", "Shilling"], correct: "Rand" },
    { question: "Which flightless bird species is natively found in Antarctica?", answers: ["Ostrich", "Emu", "Penguin", "Kiwi"], correct: "Penguin" },
    { question: "What subatomic particle carries a distinct negative electrical charge?", answers: ["Proton", "Neutron", "Electron", "Quark"], correct: "Electron" },
    { question: "Which primary structural layer forms the outside shell of Earth?", answers: ["Core", "Mantle", "Crust", "Atmosphere"], correct: "Crust" },
    { question: "What color category results from blending yellow and blue paints?", answers: ["Red", "Orange", "Green", "Purple"], correct: "Green" },
    { question: "What is the official capital city of Australia?", answers: ["Sydney", "Melbourne", "Brisbane", "Canberra"], correct: "Canberra" },
    { question: "Which country originally invented the modern sport of golf?", answers: ["England", "Ireland", "United States", "Scotland"], correct: "Scotland" },
    { question: "How many structural bones form an adult human body framework?", answers: ["186", "206", "146", "216"], correct: "206" },
    { question: "Which specific land mammal is currently the fastest in short sprints?", answers: ["Lion", "Leopard", "Pronghorn", "Cheetah"], correct: "Cheetah" },
    { question: "What is the small country container that holds Vatican City?", answers: ["France", "Spain", "Monaco", "Italy"], correct: "Italy" },
    { question: "Which cosmic galaxy contains our solar system and planet?", answers: ["Andromeda", "Triangulum", "Sombrero", "Milky Way"], correct: "Milky Way" },
    { question: "What structural tissue bands anchor human muscles onto skeletal bones?", answers: ["Cartilage", "Ligaments", "Fascia", "Tendons"], correct: "Tendons" },
    { question: "Which planet inside our neighborhood sits furthest away from the Sun?", answers: ["Jupiter", "Saturn", "Uranus", "Neptune"], correct: "Neptune" },
    { question: "What specific currency system is used throughout Australia?", answers: ["Pound", "Euro", "Yen", "Australian Dollar"], correct: "Australian Dollar" },
    { question: "Which specific dynamic organ manages balance inside humans?", answers: ["Eyes", "Brain stem", "Spine", "Inner Ear"], correct: "Inner Ear" },
    { question: "What specific gaseous item forms standard domestic candle wax?", answers: ["Oxygen", "Nitrogen", "Methane", "Paraffin Hydrocarbons"], correct: "Paraffin Hydrocarbons" },
    { question: "Which primary bird species is historically famous for hunting snakes?", answers: ["Hawk", "Eagle", "Falcon", "Secretary Bird"], correct: "Secretary Bird" },
    { question: "What specific chemical element holds the single-letter symbol 'C'?", answers: ["Calcium", "Copper", "Chlorine", "Carbon"], correct: "Carbon" },
    { question: "Which specific historic timeline folder contains the Pyramids?", answers: ["Middle Ages", "Renaissance", "Industrial Era", "Ancient Egypt"], correct: "Ancient Egypt" },
    { question: "What basic temperature setting defines water boiling in Celsius?", answers: ["0 °C", "50 °C", "90 °C", "100 °C"], correct: "100 °C" },
    { question: "Which system pathway transports fluid sap down plant stems?", answers: ["Xylem", "Stomata", "Epidermis", "Phloem"], correct: "Phloem" },
    { question: "What specific geometric element bounds a circle's outer perimeter?", answers: ["Radius", "Diameter", "Area", "Circumference"], correct: "Circumference" },
    { question: "Which chemical structural formula holds the symbol 'Ag'?", answers: ["Gold", "Iron", "Mercury", "Silver"], correct: "Silver" },
    { question: "What primary liquid type acts as the absolute baseline for all life?", answers: ["Milk", "Juice", "Oil", "Water"], correct: "Water" },
    { question: "Which subatomic elements possess no electrical charges whatsoever?", answers: ["Protons", "Electrons", "Positrons", "Neutrons"], correct: "Neutrons" },
    { question: "What primary structural item forms the central column of plants?", answers: ["Leaves", "Roots", "Flowers", "Stem"], correct: "Stem" },
    { question: "Which system framework processes nutrient materials inside humans?", answers: ["Nervous", "Circulatory", "Respiratory", "Digestive"], correct: "Digestive" },
    { question: "What specific tool is designed to scale small graphics upwards?", answers: ["Mirror", "Prism", "Filter", "Magnifying Glass"], correct: "Magnifying Glass" },
    { question: "Which specific mineral category constitutes domestic white chalk?", answers: ["Quartz", "Granite", "Gypsum", "Calcium Carbonate"], correct: "Calcium Carbonate" },
    { question: "What mathematical property defines a shape with equal sides?", answers: ["Asymmetrical", "Scalene", "Irregular", "Equilateral"], correct: "Equilateral" },
    { question: "Sound waves travel significantly faster through water than air.", answers: ["True", "False"], correct: "True" },
    { question: "A structural flash of lightning is actually hotter than the Sun's surface.", answers: ["True", "False"], correct: "True" },
    { question: "The specific element Oxygen constitutes about 21% of our air layers.", answers: ["True", "False"], correct: "True" },
    { question: "An organic molecule must structurally contain the element Carbon.", answers: ["True", "False"], correct: "True" },
    { question: "Light particles travel significantly faster than physical sound waves.", answers: ["True", "False"], correct: "True" },
    { question: "The human heart possesses exactly four internal muscular chambers.", answers: ["True", "False"], correct: "True" },
    { question: "Water molecules expand in absolute volume whenever they freeze solid.", answers: ["True", "False"], correct: "True" },
    { question: "The planet Jupiter possesses a massive storm called the Great Red Spot.", answers: ["True", "False"], correct: "True" },
    { question: "Deciduous tree varieties fully drop their leaves during autumn seasons.", answers: ["True", "False"], correct: "True" },
    { question: "Spiders are arachnids, meaning they sit outside the true insect group.", answers: ["True", "False"], correct: "True" },
    { question: "Sharks are officially classified as aquatic marine mammals.", answers: ["True", "False"], correct: "False" },
    { question: "The Great Wall of China is clearly visible from space with the naked eye.", answers: ["True", "False"], correct: "False" },
    { question: "An adult human body has significantly more bones than a newborn infant.", answers: ["True", "False"], correct: "False" },
    { question: "The planet Venus is located closest to our central Sun neighborhood.", answers: ["True", "False"], correct: "False" },
    { question: "Sound vibrations can travel fluidly through empty cosmic space vacuums.", answers: ["True", "False"], correct: "False" },
    { question: "Every single triangle shape must possess exactly one right angle corner.", answers: ["True", "False"], correct: "False" },
    { question: "Bananas naturally grow upwards on massive woody perennial trees.", answers: ["True", "False"], correct: "False" },
    { question: "The standard chemical symbol designated for the element Iron is 'Ir'.", answers: ["True", "False"], correct: "False" },
    { question: "Lightning strikes are completely incapable of hitting the same spot twice.", answers: ["True", "False"], correct: "False" },
    { question: "All existing mammal species natively give birth to live newborn offspring.", answers: ["True", "False"], correct: "False" }
];